'use strict';

const MINECRAFT_BLOCK_CATALOG = [
  { id: 'mc_oak_planks', label: 'オークの板材', color: '#b8945f', aliases: ['oak', 'planks', 'wood', 'オーク', '板材', '木材'] },
  { id: 'mc_spruce_planks', label: 'トウヒの板材', color: '#76502f', aliases: ['spruce', 'トウヒ'] },
  { id: 'mc_birch_planks', label: 'シラカバの板材', color: '#d8c28a', aliases: ['birch', 'シラカバ'] },
  { id: 'mc_jungle_planks', label: 'ジャングルの板材', color: '#b9825b', aliases: ['jungle', 'ジャングル'] },
  { id: 'mc_acacia_planks', label: 'アカシアの板材', color: '#c46d3f', aliases: ['acacia', 'アカシア'] },
  { id: 'mc_dark_oak_planks', label: 'ダークオークの板材', color: '#4b2f1f', aliases: ['dark oak', 'ダークオーク'] },
  { id: 'mc_mangrove_planks', label: 'マングローブの板材', color: '#8f3d35', aliases: ['mangrove', 'マングローブ'] },
  { id: 'mc_cherry_planks', label: 'サクラの板材', color: '#e8a6bb', aliases: ['cherry', 'sakura', 'サクラ', '桜'] },
  { id: 'mc_bamboo_planks', label: '竹の板材', color: '#c8b84d', aliases: ['bamboo', '竹'] },
  { id: 'mc_crimson_planks', label: '真紅の板材', color: '#7a2c52', aliases: ['crimson', '真紅'] },
  { id: 'mc_warped_planks', label: '歪んだ板材', color: '#2f8f8b', aliases: ['warped', '歪んだ'] },
  { id: 'mc_stone', label: '石', color: '#7d7d7d', aliases: ['stone', '石'] },
  { id: 'mc_cobblestone', label: '丸石', color: '#686868', aliases: ['cobblestone', '丸石'] },
  { id: 'mc_mossy_cobblestone', label: '苔むした丸石', color: '#5f7a55', aliases: ['mossy', '苔'] },
  { id: 'mc_stone_bricks', label: '石レンガ', color: '#777a76', aliases: ['stone bricks', '石レンガ'] },
  { id: 'mc_deepslate', label: '深層岩', color: '#3c3f46', aliases: ['deepslate', '深層岩'] },
  { id: 'mc_blackstone', label: 'ブラックストーン', color: '#25222a', aliases: ['blackstone', 'ブラックストーン'] },
  { id: 'mc_andesite', label: '安山岩', color: '#898984', aliases: ['andesite', '安山岩'] },
  { id: 'mc_diorite', label: '閃緑岩', color: '#d7d7d2', aliases: ['diorite', '閃緑岩'] },
  { id: 'mc_granite', label: '花崗岩', color: '#a66f5d', aliases: ['granite', '花崗岩'] },
  { id: 'mc_calcite', label: '方解石', color: '#eee7dc', aliases: ['calcite', '方解石'] },
  { id: 'mc_tuff', label: '凝灰岩', color: '#62675f', aliases: ['tuff', '凝灰岩'] },
  { id: 'mc_dripstone', label: '鍾乳石ブロック', color: '#8c6b55', aliases: ['dripstone', '鍾乳石'] },
  { id: 'mc_grass_block', label: '草ブロック', color: '#6aaa40', aliases: ['grass', '草'] },
  { id: 'mc_dirt', label: '土', color: '#866043', aliases: ['dirt', '土'] },
  { id: 'mc_podzol', label: 'ポドゾル', color: '#745235', aliases: ['podzol', 'ポドゾル'] },
  { id: 'mc_mycelium', label: '菌糸', color: '#826f86', aliases: ['mycelium', '菌糸'] },
  { id: 'mc_sand', label: '砂', color: '#dacea0', aliases: ['sand', '砂'] },
  { id: 'mc_red_sand', label: '赤い砂', color: '#bf7440', aliases: ['red sand', '赤い砂'] },
  { id: 'mc_gravel', label: '砂利', color: '#85817e', aliases: ['gravel', '砂利'] },
  { id: 'mc_clay', label: '粘土', color: '#a8b0bf', aliases: ['clay', '粘土'] },
  { id: 'mc_snow', label: '雪', color: '#f0f4f8', aliases: ['snow', '雪'] },
  { id: 'mc_ice', label: '氷', color: '#9cd4ff', aliases: ['ice', '氷'] },
  { id: 'mc_packed_ice', label: '氷塊', color: '#70b7ee', aliases: ['packed ice', '氷塊'] },
  { id: 'mc_blue_ice', label: '青氷', color: '#5fa9ff', aliases: ['blue ice', '青氷'] },
  { id: 'mc_coal_block', label: '石炭ブロック', color: '#1b1b1d', aliases: ['coal block', '石炭'] },
  { id: 'mc_iron_block', label: '鉄ブロック', color: '#d8d8d0', aliases: ['iron', '鉄'] },
  { id: 'mc_copper_block', label: '銅ブロック', color: '#c8754a', aliases: ['copper', '銅'] },
  { id: 'mc_exposed_copper', label: '風化した銅', color: '#9d7d63', aliases: ['exposed copper', '風化銅'] },
  { id: 'mc_oxidized_copper', label: '酸化した銅', color: '#58a898', aliases: ['oxidized copper', '酸化銅'] },
  { id: 'mc_gold_block', label: '金ブロック', color: '#f4cc3d', aliases: ['gold', '金'] },
  { id: 'mc_diamond_block', label: 'ダイヤモンドブロック', color: '#65dce8', aliases: ['diamond', 'ダイヤ'] },
  { id: 'mc_emerald_block', label: 'エメラルドブロック', color: '#32c765', aliases: ['emerald', 'エメラルド'] },
  { id: 'mc_lapis_block', label: 'ラピスラズリブロック', color: '#2448a8', aliases: ['lapis', 'ラピス'] },
  { id: 'mc_redstone_block', label: 'レッドストーンブロック', color: '#c51f1f', aliases: ['redstone', 'レッドストーン'] },
  { id: 'mc_netherite_block', label: 'ネザライトブロック', color: '#393236', aliases: ['netherite', 'ネザライト'] },
  { id: 'mc_amethyst_block', label: 'アメジストブロック', color: '#9b67d8', aliases: ['amethyst', 'アメジスト'] },
  { id: 'mc_quartz_block', label: 'クォーツブロック', color: '#eee9df', aliases: ['quartz', 'クォーツ'] },
  { id: 'mc_obsidian', label: '黒曜石', color: '#191028', aliases: ['obsidian', '黒曜石'] },
  { id: 'mc_crying_obsidian', label: '泣く黒曜石', color: '#3b1d68', aliases: ['crying obsidian', '泣く黒曜石'] },
  { id: 'mc_netherrack', label: 'ネザーラック', color: '#7c3333', aliases: ['netherrack', 'ネザーラック'] },
  { id: 'mc_soul_sand', label: 'ソウルサンド', color: '#60412f', aliases: ['soul sand', 'ソウルサンド'] },
  { id: 'mc_soul_soil', label: 'ソウルソイル', color: '#4d382d', aliases: ['soul soil', 'ソウルソイル'] },
  { id: 'mc_basalt', label: '玄武岩', color: '#4d4d55', aliases: ['basalt', '玄武岩'] },
  { id: 'mc_end_stone', label: 'エンドストーン', color: '#d9d79a', aliases: ['end stone', 'エンドストーン'] },
  { id: 'mc_purpur', label: 'プルプァブロック', color: '#aa78b5', aliases: ['purpur', 'プルプァ'] },
  { id: 'mc_prismarine', label: 'プリズマリン', color: '#5aa89b', aliases: ['prismarine', 'プリズマリン'] },
  { id: 'mc_dark_prismarine', label: 'ダークプリズマリン', color: '#315f59', aliases: ['dark prismarine', 'ダークプリズマリン'] },
  { id: 'mc_sea_lantern', label: 'シーランタン', color: '#c7f0e8', aliases: ['sea lantern', 'シーランタン'] },
  { id: 'mc_glowstone', label: 'グロウストーン', color: '#d8aa49', aliases: ['glowstone', 'グロウストーン'] },
  { id: 'mc_shroomlight', label: 'シュルームライト', color: '#e2824e', aliases: ['shroomlight', 'シュルームライト'] },
  { id: 'mc_glass', label: 'ガラス', color: '#d7f5ff', aliases: ['glass', 'ガラス'] },
  { id: 'mc_tinted_glass', label: '遮光ガラス', color: '#4d4359', aliases: ['tinted glass', '遮光ガラス'] },
  { id: 'mc_white_wool', label: '白色の羊毛', color: '#f0f0ee', aliases: ['white wool', 'white', '白'] },
  { id: 'mc_orange_wool', label: '橙色の羊毛', color: '#f08a24', aliases: ['orange wool', 'orange', 'オレンジ', '橙'] },
  { id: 'mc_magenta_wool', label: '赤紫色の羊毛', color: '#c64fbd', aliases: ['magenta wool', 'magenta', 'マゼンタ', '赤紫'] },
  { id: 'mc_light_blue_wool', label: '空色の羊毛', color: '#5ca5d6', aliases: ['light blue wool', 'light blue', '空色', '水色'] },
  { id: 'mc_yellow_wool', label: '黄色の羊毛', color: '#f2cf3a', aliases: ['yellow wool', 'yellow', '黄色'] },
  { id: 'mc_lime_wool', label: '黄緑色の羊毛', color: '#70c837', aliases: ['lime wool', 'lime', '黄緑'] },
  { id: 'mc_pink_wool', label: '桃色の羊毛', color: '#ed8dac', aliases: ['pink wool', 'pink', 'ピンク', '桃色'] },
  { id: 'mc_gray_wool', label: '灰色の羊毛', color: '#4b5156', aliases: ['gray wool', 'gray', 'grey', '灰色'] },
  { id: 'mc_light_gray_wool', label: '薄灰色の羊毛', color: '#9aa0a0', aliases: ['light gray wool', 'light gray', '薄灰色'] },
  { id: 'mc_cyan_wool', label: '青緑色の羊毛', color: '#178b8f', aliases: ['cyan wool', 'cyan', 'シアン', '青緑'] },
  { id: 'mc_purple_wool', label: '紫色の羊毛', color: '#7e3db5', aliases: ['purple wool', 'purple', '紫'] },
  { id: 'mc_blue_wool', label: '青色の羊毛', color: '#304cb2', aliases: ['blue wool', 'blue', '青'] },
  { id: 'mc_brown_wool', label: '茶色の羊毛', color: '#765432', aliases: ['brown wool', 'brown', '茶色'] },
  { id: 'mc_green_wool', label: '緑色の羊毛', color: '#557d2b', aliases: ['green wool', 'green', '緑'] },
  { id: 'mc_red_wool', label: '赤色の羊毛', color: '#b92d2b', aliases: ['red wool', 'red', '赤'] },
  { id: 'mc_black_wool', label: '黒色の羊毛', color: '#1d1d22', aliases: ['black wool', 'black', '黒'] },
  { id: 'mc_terracotta', label: 'テラコッタ', color: '#9f5d45', aliases: ['terracotta', 'テラコッタ'] },
  { id: 'mc_white_concrete', label: '白色のコンクリート', color: '#e5e8e8', aliases: ['white concrete', '白コンクリート'] },
  { id: 'mc_black_concrete', label: '黒色のコンクリート', color: '#08090e', aliases: ['black concrete', '黒コンクリート'] },
  { id: 'mc_red_concrete', label: '赤色のコンクリート', color: '#8f2020', aliases: ['red concrete', '赤コンクリート'] },
  { id: 'mc_blue_concrete', label: '青色のコンクリート', color: '#233c9b', aliases: ['blue concrete', '青コンクリート'] },
  { id: 'mc_green_concrete', label: '緑色のコンクリート', color: '#495b24', aliases: ['green concrete', '緑コンクリート'] },
  { id: 'mc_light_blue_concrete', label: '空色のコンクリート', color: '#2389c6', aliases: ['light blue concrete', '水色コンクリート'] },
  { id: 'mc_pink_concrete', label: '桃色のコンクリート', color: '#d5658f', aliases: ['pink concrete', 'ピンクコンクリート'] },
  { id: 'mc_purple_concrete', label: '紫色のコンクリート', color: '#641f9c', aliases: ['purple concrete', '紫コンクリート'] },
  { id: 'mc_yellow_concrete', label: '黄色のコンクリート', color: '#f0b820', aliases: ['yellow concrete', '黄色コンクリート'] },
  { id: 'mc_honey_block', label: 'ハチミツブロック', color: '#f2a51f', aliases: ['honey', 'ハチミツ'] },
  { id: 'mc_slime_block', label: 'スライムブロック', color: '#72d262', aliases: ['slime', 'スライム'] },
  { id: 'mc_sculk', label: 'スカルク', color: '#062b36', aliases: ['sculk', 'スカルク'] },
];

const MINECRAFT_ITEM_CATALOG = [
  { id: 'mc_stick', label: '棒', color: '#9a6b3c' },
  { id: 'mc_coal', label: '石炭', color: '#202024' },
  { id: 'mc_charcoal', label: '木炭', color: '#292526' },
  { id: 'mc_raw_iron', label: '鉄の原石', color: '#c98f68' },
  { id: 'mc_iron_ingot', label: '鉄インゴット', color: '#d8d8d0' },
  { id: 'mc_raw_copper', label: '銅の原石', color: '#c8754a' },
  { id: 'mc_copper_ingot', label: '銅インゴット', color: '#d88752' },
  { id: 'mc_raw_gold', label: '金の原石', color: '#d6a13a' },
  { id: 'mc_gold_ingot', label: '金インゴット', color: '#f4cc3d' },
  { id: 'mc_diamond', label: 'ダイヤモンド', color: '#65dce8' },
  { id: 'mc_emerald', label: 'エメラルド', color: '#32c765' },
  { id: 'mc_lapis_lazuli', label: 'ラピスラズリ', color: '#2448a8' },
  { id: 'mc_redstone_dust', label: 'レッドストーンダスト', color: '#c51f1f' },
  { id: 'mc_quartz', label: 'ネザークォーツ', color: '#eee9df' },
  { id: 'mc_amethyst_shard', label: 'アメジストの欠片', color: '#9b67d8' },
  { id: 'mc_netherite_scrap', label: 'ネザライトの欠片', color: '#4a3a3a' },
  { id: 'mc_netherite_ingot', label: 'ネザライトインゴット', color: '#393236' },
  { id: 'mc_wooden_sword', label: '木の剣', color: '#b8945f' },
  { id: 'mc_stone_sword', label: '石の剣', color: '#777777' },
  { id: 'mc_iron_sword', label: '鉄の剣', color: '#d8d8d0' },
  { id: 'mc_golden_sword', label: '金の剣', color: '#f4cc3d' },
  { id: 'mc_diamond_sword', label: 'ダイヤの剣', color: '#65dce8' },
  { id: 'mc_netherite_sword', label: 'ネザライトの剣', color: '#393236' },
  { id: 'mc_pickaxe_set', label: '各種ツルハシ', color: '#8d8d8d' },
  { id: 'mc_axe_set', label: '各種斧', color: '#8d8d8d' },
  { id: 'mc_shovel_set', label: '各種シャベル', color: '#8d8d8d' },
  { id: 'mc_hoe_set', label: '各種クワ', color: '#8d8d8d' },
  { id: 'mc_bow', label: '弓', color: '#8b5a2b' },
  { id: 'mc_crossbow', label: 'クロスボウ', color: '#9a6b3c' },
  { id: 'mc_arrow', label: '矢', color: '#d7dce2' },
  { id: 'mc_trident', label: 'トライデント', color: '#6cb7bf' },
  { id: 'mc_shield', label: '盾', color: '#b9bec8' },
  { id: 'mc_bucket', label: 'バケツ', color: '#bac2c9' },
  { id: 'mc_water_bucket', label: '水入りバケツ', color: '#2f8fe8' },
  { id: 'mc_lava_bucket', label: '溶岩入りバケツ', color: '#f05a24' },
  { id: 'mc_flint_and_steel', label: '火打石と打ち金', color: '#b0a17d' },
  { id: 'mc_compass', label: 'コンパス', color: '#de3b3b' },
  { id: 'mc_clock', label: '時計', color: '#d2a63a' },
  { id: 'mc_map', label: '地図', color: '#d7c08b' },
  { id: 'mc_totem', label: '不死のトーテム', color: '#d8b34d' },
  { id: 'mc_elytra', label: 'エリトラ', color: '#b2a6d9' },
  { id: 'mc_firework_rocket', label: '花火のロケット', color: '#e65a5a' },
  { id: 'mc_ender_pearl', label: 'エンダーパール', color: '#1ed6aa' },
  { id: 'mc_eye_of_ender', label: 'エンダーアイ', color: '#69d84f' },
  { id: 'mc_blaze_rod', label: 'ブレイズロッド', color: '#ffb02e' },
  { id: 'mc_blaze_powder', label: 'ブレイズパウダー', color: '#ffd05a' },
  { id: 'mc_nether_wart', label: 'ネザーウォート', color: '#8e1731' },
  { id: 'mc_ghast_tear', label: 'ガストの涙', color: '#e5efff' },
  { id: 'mc_magma_cream', label: 'マグマクリーム', color: '#f2b64b' },
  { id: 'mc_brewing_stand', label: '醸造台', color: '#6f5a48' },
  { id: 'mc_potion_set', label: '各種ポーション', color: '#9bd8ff' },
  { id: 'mc_apple', label: 'リンゴ', color: '#c43a36' },
  { id: 'mc_golden_apple', label: '金のリンゴ', color: '#ffd94a' },
  { id: 'mc_bread', label: 'パン', color: '#c58a48' },
  { id: 'mc_cooked_beef', label: 'ステーキ', color: '#8d3c2d' },
  { id: 'mc_carrot', label: 'ニンジン', color: '#e78a2e' },
  { id: 'mc_potato', label: 'ジャガイモ', color: '#b98a4c' },
  { id: 'mc_wheat', label: '小麦', color: '#d8b858' },
  { id: 'mc_seeds', label: '種', color: '#5f8f31' },
  { id: 'mc_bone', label: '骨', color: '#e8e2cf' },
  { id: 'mc_string', label: '糸', color: '#d8d8d8' },
  { id: 'mc_leather', label: '革', color: '#9b5a2d' },
  { id: 'mc_feather', label: '羽根', color: '#e6e6df' },
  { id: 'mc_gunpowder', label: '火薬', color: '#585858' },
  { id: 'mc_slime_ball', label: 'スライムボール', color: '#72d262' },
  { id: 'mc_prismarine_shard', label: 'プリズマリンの欠片', color: '#5aa89b' },
  { id: 'mc_nautilus_shell', label: 'オウムガイの殻', color: '#d6c2a0' },
  { id: 'mc_heart_of_the_sea', label: '海洋の心', color: '#4fc7d8' },
  { id: 'mc_saddle', label: 'サドル', color: '#8b4a30' },
  { id: 'mc_name_tag', label: '名札', color: '#d4c49a' },
  { id: 'mc_music_disc', label: 'レコード各種', color: '#222222' },
  { id: 'mc_spawn_egg_set', label: 'スポーンエッグ各種', color: '#d58bd8' },
];

const MINECRAFT_GENERAL_CATALOG = MINECRAFT_BLOCK_CATALOG.concat(MINECRAFT_ITEM_CATALOG);
